export interface Business {
  id: string;
  slug: string;
  name: string;
  category: string;
  location: string;
  address?: string;
  phone?: string;
  hours?: string;
  rating: number;
  reviewCount: number;
  reviewCountFormatted: string;
  photoCount?: number;
  description: string;
  badge?: "Terverifikasi" | "Pilihan Pengguna";
  initials: string;
  color: string;
  features?: string[];
}

export const businesses: Business[] = [
  {
    id: "0",
    slug: "sunny-cafe",
    name: "Sunny Cafe",
    category: "Kafe & Restoran",
    location: "Jakarta Selatan",
    address: "Jl. Melawai Raya No. 12, Jakarta Selatan 12160",
    phone: undefined,
    hours: "-",
    rating: 0,
    reviewCount: 0,
    reviewCountFormatted: "0 ulasan",
    photoCount: 0,
    description: "-",
    badge: "Terverifikasi",
    initials: "SC",
    color: "bg-amber-100 text-amber-900 border-amber-200",
    features: []
  },
  {
    id: "1",
    slug: "the-daily-bean",
    name: "The Daily Bean",
    category: "Restoran",
    location: "Jakarta Selatan",
    address: "Jl. Senopati No. 45, Jakarta Selatan 12190",
    phone: undefined,
    hours: "-",
    rating: 0,
    reviewCount: 0,
    reviewCountFormatted: "0 ulasan",
    photoCount: 0,
    description: "-",
    badge: "Terverifikasi",
    initials: "DB",
    color: "bg-amber-900 text-white",
    features: []
  },
  {
    id: "2",
    slug: "hotel-santika-premiere",
    name: "Hotel Santika Premiere",
    category: "Hotel",
    location: "Jakarta Pusat",
    address: "Jl. Slipi No. 2, Jakarta Pusat 10260",
    phone: undefined,
    hours: "-",
    rating: 0,
    reviewCount: 0,
    reviewCountFormatted: "0 ulasan",
    photoCount: 0,
    description: "-",
    badge: "Pilihan Pengguna",
    initials: "HS",
    color: "bg-blue-900 text-white",
    features: []
  },
  {
    id: "3",
    slug: "glow-beauty-clinic",
    name: "Glow Beauty Clinic",
    category: "Kecantikan",
    location: "Jakarta Selatan",
    address: "Jl. Kemang Raya No. 88, Jakarta Selatan 12730",
    phone: "+62 813 4455 6677",
    hours: "Senin - Sabtu, 09:00 - 19:00",
    rating: 4.8,
    reviewCount: 3600,
    reviewCountFormatted: "3.6k ulasan",
    photoCount: 240,
    description: "Perawatan profesional dengan hasil yang memuaskan. Staf sangat ramah dan informatif.",
    badge: "Terverifikasi",
    initials: "GB",
    color: "bg-pink-600 text-white",
    features: ["Konsultasi Gratis", "Dokter Spesialis", "Alat Modern", "Parkir"]
  },
  {
    id: "4",
    slug: "toko-elektronik-mega",
    name: "Toko Elektronik Mega",
    category: "Elektronik",
    location: "Bandung",
    address: "Jl. Dago No. 102, Bandung 40132",
    phone: "+62 22 420 8899",
    hours: "Setiap hari, 09:00 - 21:00",
    rating: 4.6,
    reviewCount: 5200,
    reviewCountFormatted: "5.2k ulasan",
    photoCount: 310,
    description: "Produk lengkap, harga bersaing, dan pelayanan cepat. Sangat recommended!",
    badge: "Terverifikasi",
    initials: "EM",
    color: "bg-sky-600 text-white",
    features: ["Garansi Resmi", "Pengiriman Cepat", "Cicilan 0%", "Layanan Purna Jual"]
  },
  {
    id: "5",
    slug: "loka-wisata-tour-travel",
    name: "Loka Wisata Tour & Travel",
    category: "Travel & Wisata",
    location: "Yogyakarta",
    address: "Jl. Malioboro No. 15, Yogyakarta 55271",
    phone: "+62 274 555 123",
    hours: "Setiap hari, 08:00 - 20:00",
    rating: 4.7,
    reviewCount: 1900,
    reviewCountFormatted: "1.9k ulasan",
    photoCount: 420,
    description: "Paket wisata lengkap dengan harga terjangkau. Tour guide sangat profesional.",
    badge: "Pilihan Pengguna",
    initials: "LW",
    color: "bg-[#008767] text-white",
    features: ["Custom Tour", "Pemandu Wisata", "Antar Jemput Bandara", "Asuransi Perjalanan"]
  },
  {
    id: "6",
    slug: "zara-fashion",
    name: "Zara Fashion",
    category: "Fashion",
    location: "Jakarta Pusat",
    address: "Grand Indonesia Mall, Jakarta Pusat 10310",
    phone: "+62 21 2358 0000",
    hours: "Setiap hari, 10:00 - 22:00",
    rating: 4.4,
    reviewCount: 2600,
    reviewCountFormatted: "2.6k ulasan",
    photoCount: 180,
    description: "Koleksi lengkap, kualitas bagus, dan sering ada promo menarik.",
    badge: "Terverifikasi",
    initials: "ZF",
    color: "bg-stone-900 text-white",
    features: ["Fitting Room", "Fitting Assistance", "Refund Policy", "Membership"]
  },
  {
    id: "83bd00c3-3335-4c45-af73-01ba8dcf9f13",
    slug: "ponty-rental-mobil-bandung",
    name: "Ponty Rental Mobil Bandung",
    category: "Jasa & Rental Mobil",
    location: "Bandung, Jawa Barat",
    address: "Jl. Soekarno Hatta No. 123, Pasirluyu, Bandung",
    phone: "+62 812 3456 789",
    hours: "24 Jam",
    rating: 4.8,
    reviewCount: 1248,
    reviewCountFormatted: "1.248 ulasan",
    photoCount: 150,
    description: "Penyedia jasa sewa dan rental mobil terpercaya di Bandung dengan armada bersih, wangi, terawat, dan supir berpengalaman.",
    badge: "Terverifikasi",
    initials: "PR",
    color: "bg-[#008767] text-white",
    features: ["Sewa Lepas Kunci", "Dengan Supir", "Antar Jemput Bandara", "Asuransi All-Risk", "Pelayanan 24 Jam"]
  },
  {
    id: "trac-rental-1",
    slug: "trac-astra-car-rental",
    name: "TRAC Astra Car Rental",
    category: "Jasa & Rental Mobil",
    location: "Jakarta & Bandung",
    address: "Jl. M.H. Thamrin No. 8, Jakarta Pusat",
    phone: "+62 21 1500 009",
    hours: "24 Jam",
    rating: 4.9,
    reviewCount: 3820,
    reviewCountFormatted: "3.8k ulasan",
    photoCount: 310,
    description: "Solusi transportasi terpercaya untuk kebutuhan sewa mobil harian, bulanan, dan perjalanan bisnis keluarga.",
    badge: "Pilihan Pengguna",
    initials: "TR",
    color: "bg-blue-800 text-white",
    features: ["Lepas Kunci", "Drive with Chauffeur", "Emergency Assistance 24/7", "Unit Terbaru"]
  },
  {
    id: "d955a5ae-0c10-4b56-ad1d-6bf90d8e8a1d",
    slug: "sheraton-bandung-hotel-towers",
    name: "Sheraton Bandung Hotel & Towers",
    category: "Hotel & Akomodasi",
    location: "Bandung City, West Java",
    address: "Jl. Ir. H. Juanda No. 390, Dago, Bandung",
    phone: "+62 22 250 0303",
    hours: "24 Jam",
    rating: 4.7,
    reviewCount: 1950,
    reviewCountFormatted: "1.95k ulasan",
    photoCount: 420,
    description: "Hotel bintang 5 di kawasan Dago Bandung dengan suasana asri resort, kolam renang spektakuler, dan restoran internasional.",
    badge: "Terverifikasi",
    initials: "SB",
    color: "bg-emerald-900 text-white",
    features: ["Resort Pool", "Spa & Wellness", "Kids Club", "Buffet Breakfast", "Free High Speed WiFi"]
  },
  {
    id: "7",
    slug: "autocare-service",
    name: "AutoCare Service",
    category: "Otomotif",
    location: "Surabaya",
    address: "Jl. Raya Gubeng No. 34, Surabaya 60281",
    phone: "+62 31 503 9988",
    hours: "Senin - Sabtu, 08:00 - 17:00",
    rating: 4.5,
    reviewCount: 3200,
    reviewCountFormatted: "3.2k ulasan",
    photoCount: 150,
    description: "Pelayanan cepat, teknisi berpengalaman, dan harga transparan.",
    badge: "Terverifikasi",
    initials: "AC",
    color: "bg-indigo-700 text-white",
    features: ["Garansi Servis", "Ruang Tunggu Ber-AC", "Suku Cadang Asli", "Cuci Mobil"]
  },
  {
    id: "8",
    slug: "sushi-hiro",
    name: "Sushi Hiro",
    category: "Restoran",
    location: "Jakarta Utara",
    address: "PIK Avenue Mall, Jakarta Utara 14470",
    phone: "+62 21 2257 0111",
    hours: "Setiap hari, 11:00 - 22:00",
    rating: 4.8,
    reviewCount: 4100,
    reviewCountFormatted: "4.1k ulasan",
    photoCount: 650,
    description: "Rasa autentik, bahan berkualitas, dan suasana sangat nyaman.",
    badge: "Terverifikasi",
    initials: "SH",
    color: "bg-red-600 text-white",
    features: ["Halal Certified Option", "Private Dining", "WiFi Gratis", "Ocha Refill"]
  },
  {
    id: "9",
    slug: "serenity-spa",
    name: "Serenity Spa",
    category: "Kesehatan",
    location: "Bali",
    address: "Jl. Raya Seminyak No. 12, Bali 80361",
    phone: "+62 361 730 888",
    hours: "Setiap hari, 09:00 - 21:00",
    rating: 4.7,
    reviewCount: 2300,
    reviewCountFormatted: "2.3k ulasan",
    photoCount: 380,
    description: "Tempat yang cocok untuk relaksasi. Terapis profesional dan suasana tenang.",
    badge: "Pilihan Pengguna",
    initials: "SS",
    color: "bg-emerald-700 text-white",
    features: ["Aromaterapi", "Private Treatment Room", "Welcome Drink", "Shower Room"]
  },
  {
    id: "10",
    slug: "tokopedia",
    name: "Tokopedia",
    category: "E-Commerce",
    location: "Jakarta Selatan",
    address: "Tokopedia Tower, Ciputra World 2, Jakarta Selatan",
    phone: "+62 21 5081 3333",
    hours: "24 Jam Online",
    rating: 4.6,
    reviewCount: 12400,
    reviewCountFormatted: "12.4k ulasan",
    photoCount: 1200,
    description: "Situs belanja online terpercaya di Indonesia dengan jutaan produk berkualitas.",
    badge: "Terverifikasi",
    initials: "TP",
    color: "bg-emerald-600 text-white",
    features: ["Bebas Ongkir", "Garansi Resmi", "Beragam Metode Pembayaran", "24/7 Support"]
  },
  {
    id: "11",
    slug: "shopee",
    name: "Shopee",
    category: "E-Commerce",
    location: "Jakarta Selatan",
    address: "Pacific Century Place, SCBD, Jakarta Selatan",
    phone: "+62 21 3950 0300",
    hours: "24 Jam Online",
    rating: 4.5,
    reviewCount: 10300,
    reviewCountFormatted: "10.3k ulasan",
    photoCount: 950,
    description: "Platform e-commerce terkemuka di Asia Tenggara dengan penawaran menarik setiap hari.",
    badge: "Pilihan Pengguna",
    initials: "SP",
    color: "bg-orange-600 text-white",
    features: ["Cashback Extra", "Gratis Ongkir Rp0", "ShopeePay", "Live Stream Shopping"]
  },
  {
    id: "12",
    slug: "traveloka",
    name: "Traveloka",
    category: "Travel & Wisata",
    location: "Jakarta Barat",
    address: "Wisma Barito Pacific, Slipi, Jakarta Barat",
    phone: "+62 804 1500 777",
    hours: "24 Jam Customer Service",
    rating: 4.7,
    reviewCount: 8900,
    reviewCountFormatted: "8.9k ulasan",
    photoCount: 780,
    description: "Pemesanan tiket pesawat, hotel, dan atraksi wisata termudah dan terpercaya.",
    badge: "Terverifikasi",
    initials: "TV",
    color: "bg-sky-500 text-white",
    features: ["Reschedule Mudah", "Refund Cepat", "PayLater", "Asuransi Perjalanan"]
  },
  {
    id: "13",
    slug: "iphone-17",
    name: "iPhone 17",
    category: "Elektronik",
    location: "Jakarta Pusat",
    address: "Apple Official Store / Authorized Reseller",
    phone: "+62 800 186 7753",
    hours: "Setiap hari, 10:00 - 22:00",
    rating: 4.8,
    reviewCount: 6400,
    reviewCountFormatted: "6.4k ulasan",
    photoCount: 450,
    description: "Smartphone flagship tercanggih dengan sistem kamera mutakhir dan daya tahan baterai terbaik.",
    badge: "Terverifikasi",
    initials: "i17",
    color: "bg-slate-900 text-white",
    features: ["Garansi Apple 1 Tahun", "Chipset A19 Bionic", "Kamera 48MP", "Titanium Frame"]
  },
  {
    id: "14",
    slug: "indomaret",
    name: "Indomaret",
    category: "Minimarket",
    location: "Nasional",
    address: "Menara Indomaret, PIK, Jakarta Utara",
    phone: "+62 1500 280",
    hours: "24 Jam / 07:00 - 22:00",
    rating: 4.3,
    reviewCount: 5700,
    reviewCountFormatted: "5.7k ulasan",
    photoCount: 300,
    description: "Jaringan minimarket terbesar penyedia kebutuhan harian, pembayaran tagihan, dan i-Saku.",
    badge: "Terverifikasi",
    initials: "ID",
    color: "bg-blue-600 text-white",
    features: ["Toko 24 Jam", "Tarik Tunai", "Pembayaran Tagihan", "Point Member"]
  }
];

export function getBusinessBySlug(slug: string): Business {
  const found = businesses.find((b) => b.slug === slug);
  if (found) return found;

  // Fallback to Sunny Cafe or dynamic fallback object
  return {
    id: "0",
    slug: slug,
    name: slug.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" "),
    category: "Kafe & Restoran",
    location: "Jakarta Selatan",
    address: "Jl. Melawai Raya No. 12, Jakarta Selatan 12160",
    phone: "+62 812 3456 7890",
    hours: "Setiap hari, 07:00 - 22:00",
    rating: 4.6,
    reviewCount: 1248,
    reviewCountFormatted: "1.248 ulasan",
    photoCount: 432,
    description: `${slug} adalah tempat yang tepat untuk menikmati layanan berkualitas, makanan lezat, dan suasana yang nyaman.`,
    badge: "Terverifikasi",
    initials: slug.substring(0, 2).toUpperCase(),
    color: "bg-[#008767] text-white",
    features: ["WiFi Gratis", "Outdoor Area", "Toilet", "Parkir", "Menerima Reservasi"]
  };
}
